const NEWS_ADD = 'NEWS/ADD';
const NEWS_REMOVE = 'NEWS/REMOVE';
const NEWS_EDIT = 'NEWS/EDIT';
const NEWS_COMMENTARY_ADD = 'NEWS/COMENTARY/ADD';
const NEWS_COMMENTARY_REMOVE = 'NEWS/COMENTARY/REMOVE';

export default {
    NEWS_ADD,
    NEWS_REMOVE,
    NEWS_EDIT,
    NEWS_COMMENTARY_ADD,
    NEWS_COMMENTARY_REMOVE,
};
